---
- hosts: docker_server
  name: Install docker
  become: yes
  # è necessario eseguire un --fix-broken
  roles:
    - name: Install docker
      role: "nickjj.docker"
      tags: ["docker"]
  tasks:
    - name: update docker deamon configuration
      template:
          src: ../templates/docker.j2
          dest: /etc/default/docker
          owner: root
          group: root
          mode: '0644'
    - name: Enable Docker service
      service:
        name: docker
        enabled: yes
        state: started
